version: '3'
services:
    accessdb:
        build: accessdb/
        hostname: "accessdb"
        ports:
            - "5432"
        labels:
            NAME: "accessdb"
    limiter:
        build: limiter/
        environment:
            - DBURI=postgres://accesswriter:hu8jmn3@accessdb:5432/access_postgres_db?sslmode=disable
            - PORTNUM=80
            - LIMIT=10
            - TIMESPAN=5m
        ports:
            - "80:80"
